// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAT3sbIH3amBSN_fDzFC2jIvfsxJq_b60',
    appId: '1:570664601135:web:be38b2eb3367a77edae8da',
    messagingSenderId: '570664601135',
    projectId: 'short-videos-484701',
    authDomain: 'short-videos-484701.firebaseapp.com',
    storageBucket: 'short-videos-484701.firebasestorage.app',
    measurementId: 'G-R07MFSGWPB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnQyz-HU5vt07gMsAZ7xHvDy0N4Oi-PJA',
    appId: '1:570664601135:android:b7d9bcb70ee3e4fbdae8da',
    messagingSenderId: '570664601135',
    projectId: 'short-videos-484701',
    storageBucket: 'short-videos-484701.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoi_AObA_RcxfHgX30v1b7lhhmZJemzY8',
    appId: '1:570664601135:ios:189271104f96943cdae8da',
    messagingSenderId: '570664601135',
    projectId: 'short-videos-484701',
    storageBucket: 'short-videos-484701.firebasestorage.app',
    androidClientId: '570664601135-g6o757ht1ecqqvg2i6grhlmcj1qcd78d.apps.googleusercontent.com',
    iosBundleId: 'com.example.scalableShortVideoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoi_AObA_RcxfHgX30v1b7lhhmZJemzY8',
    appId: '1:570664601135:ios:189271104f96943cdae8da',
    messagingSenderId: '570664601135',
    projectId: 'short-videos-484701',
    storageBucket: 'short-videos-484701.firebasestorage.app',
    androidClientId: '570664601135-g6o757ht1ecqqvg2i6grhlmcj1qcd78d.apps.googleusercontent.com',
    iosBundleId: 'com.example.scalableShortVideoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAT3sbIH3amBSN_fDzFC2jIvfsxJq_b60',
    appId: '1:570664601135:web:623682f9d6af596cdae8da',
    messagingSenderId: '570664601135',
    projectId: 'short-videos-484701',
    authDomain: 'short-videos-484701.firebaseapp.com',
    storageBucket: 'short-videos-484701.firebasestorage.app',
    measurementId: 'G-Q9N1Y40YZT',
  );
}
